### ISSUE TITLE
[Suggestion] Support for displaying quadratic blocks of bits

### ISSUE THREAD

**Issue by kres0345** [danielweper/BitTools#3]
Sometimes it's useful to visualize a primitive by a block,

For example this would be the output for a WORD-type (int16)
"0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0"

The bits should go as text wraps. Possibly add support for the spots to represent a byte instead of a bit.

I wasn't sure how to file a suggestion as you don't have a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by danielweper** [comment]
So you would want an addition to BitString making it possible to print 16-bit ints as
0000
0000
0000
0000

is that correct understanding?

**Comment by kres0345** [comment]
Yeah, exactly. I was trying to implement hamming codes, and it would've been pretty useful to view the bits as a block to quickly deduct the index of a bit. Similar to how [3Blue1Brown](https://www.youtube.com/watch?v=X8jsijhllIA) displayed the bits in his video on the subject.

**Comment by danielweper** [comment]
How would you want this to work for other types (like int8, int32 and int64)?

**Comment by kres0345** [comment]
I think it would make sense for it to just scale accordingly, keeping it quadratic. Alternatively, have a fixed width of 8 (somehow arbitrary). Otherwise, maybe only implement for small types like int8 and int16

**Comment by danielweper** [comment]
You cannot have it quadratic for int8 and int32, as neither 8 nor 32 are quadratic numbers.
